language: php

php:
  - 5.6
  - 7.0

env:
  global:
    - WP_CLI_BIN_DIR=/tmp/wp-cli-phar
    - WP_CLI_CONFIG_PATH=/tmp/wp-cli-phar/config.yml
    - WP_VERSION=master
    - WP_VERSION=4.5

before_script:
  - composer install --prefer-source
  - bash ./bin/install-package-tests.sh
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - if [ $CODECLIMATE_REPO_TOKEN ]; then ./vendor/bin/test-reporter; fi;
  - ./vendor/bin/behat

cache:
  directories:
    - vendor/

notifications:
  email: false